apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    istio-injection: enabled
  name: service-graph
spec: {}
status: {}
---
apiVersion: v1
data:
  service-graph: |
    services:
    - isEntrypoint: true
      name: svc-0
      numReplicas: 1
      script:
      - - call:
            service: svc-0-0
            size: 0B
        - call:
            service: svc-0-1
            size: 0B
        - call:
            service: svc-0-2
            size: 0B
        - call:
            service: svc-0-3
            size: 0B
        - call:
            service: svc-0-4
            size: 0B
        - call:
            service: svc-0-5
            size: 0B
        - call:
            service: svc-0-6
            size: 0B
        - call:
            service: svc-0-7
            size: 0B
        - call:
            service: svc-0-8
            size: 0B
      type: http
    - name: svc-0-0
      numReplicas: 1
      type: http
    - name: svc-0-1
      numReplicas: 1
      type: http
    - name: svc-0-2
      numReplicas: 1
      type: http
    - name: svc-0-3
      numReplicas: 1
      type: http
    - name: svc-0-4
      numReplicas: 1
      type: http
    - name: svc-0-5
      numReplicas: 1
      type: http
    - name: svc-0-6
      numReplicas: 1
      type: http
    - name: svc-0-7
      numReplicas: 1
      type: http
    - name: svc-0-8
      numReplicas: 1
      type: http
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: service-graph-config
  namespace: service-graph
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-0
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-0
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-0
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-0
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-0
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-0
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-1
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-1
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-1
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-1
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-1
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-1
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-2
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-2
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-2
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-2
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-2
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-2
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-3
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-3
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-3
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-3
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-3
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-3
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-4
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-4
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-4
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-4
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-4
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-4
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-5
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-5
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-5
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-5
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-5
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-5
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-6
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-6
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-6
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-6
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-6
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-6
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-7
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-7
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-7
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-7
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-7
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-7
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-8
  namespace: service-graph
spec:
  replicas: 1
  selector:
    matchLabels:
      name: svc-0-8
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        name: svc-0-8
        role: service
    spec:
      containers:
      - args:
        - --max-idle-connections-per-host=64
        env:
        - name: SERVICE_NAME
          value: svc-0-8
        image: tahler/mock-service:latest
        name: mock-service
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      nodeSelector:
        cloud.google.com/gke-nodepool: service-graph-pool
      volumes:
      - configMap:
          items:
          - key: service-graph
            path: service-graph.yaml
          name: service-graph-config
        name: config-volume
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: service-graph
  name: svc-0-8
  namespace: service-graph
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    name: svc-0-8
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: client
  name: client
spec:
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: "2022-10-10T15:44:41Z"
      labels:
        app: client
    spec:
      containers:
      - args:
        - server
        image: tahler/fortio:prometheus
        name: fortio-client
        ports:
        - containerPort: 8080
        - containerPort: 42422
        resources: {}
      nodeSelector:
        cloud.google.com/gke-nodepool: client-pool
status: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  creationTimestamp: "2022-10-10T15:44:41Z"
  labels:
    app: client
  name: client
spec:
  ports:
  - port: 8080
    targetPort: 0
  selector:
    app: client
status:
  loadBalancer: {}
